name: Upgrades
on: [push, pull_request]
jobs:
  upgrade:
    strategy:
      matrix:
        ps-versions:
          - from: 1.6.1.11
            channel: minor
          # Failing for now
          #- from: 1.6.1.24
          #  channel: major
          - from: 1.7.6.9
            channel: major
          - from: 1.7.6.1
            channel: minor
          - from: 1.7.7.0
            channel: minor
    runs-on: ubuntu-latest
    name: Upgrade
    steps:
      - uses: actions/checkout@v2
      - name: Composer Install
        run: composer install
      - name: Upgrade & Rollback
        uses: ./.github/
